added "eval" to launch $INENGLISH makepkg 	renamed:    yaourt/AUTHORS -> src/AUTHORS 	renamed:    yaourt/COPYING -> src/COPYING 	renamed:    yaourt/INSTALL -> src/INSTALL 	renamed:    yaourt/Makefile -> src/Makefile 	renamed:    yaourt/bashcompletion -> src/bashcompletion 	renamed:    yaourt/lib/alpm_backup.sh -> src/lib/alpm_backup.sh 	renamed:    yaourt/lib/alpm_query.sh -> src/lib/alpm_query.sh 	renamed:    yaourt/lib/alpm_stats.sh -> src/lib/alpm_stats.sh 	renamed:    yaourt/lib/aur.sh -> src/lib/aur.sh 	renamed:    yaourt/lib/basicfunctions.sh -> src/lib/basicfunctions.sh 	renamed:    yaourt/lib/color.sh -> src/lib/color.sh 	renamed:    yaourt/lib/pacman_conf.sh -> src/lib/pacman_conf.sh 	renamed:    yaourt/pacdiffviewer -> src/pacdiffviewer 	renamed:    yaourt/yaourt -> src/yaourt 	renamed:    yaourt/yaourt.8 -> src/yaourt.8 	renamed:    yaourt/yaourtrc -> src/yaourtrc 	renamed:    yaourt/yaourtrc.5 -> src/yaourtrc.5 	new file:   test/PKGBUILD

diff --git a/src/yaourt b/src/yaourt
--- a/src/yaourt
+++ b/src/yaourt
@@ -244,12 +244,12 @@ fi
 
 # Build 
 if [ $runasroot -eq 1 ]; then 
-	pacman_queuing; $INENGLISH PKGDEST=`pwd` nice -n 15 makepkg $confirmation --asroot --syncdeps --force -p ./PKGBUILD
+	pacman_queuing; eval $INENGLISH PKGDEST=`pwd` nice -n 15 makepkg $confirmation --asroot --syncdeps --force -p ./PKGBUILD
 else
 	if [ $SUDOINSTALLED -eq 1 ]; then
-		pacman_queuing; $INENGLISH PKGDEST=`pwd` nice -n 15 makepkg $confirmation --syncdeps --force -p ./PKGBUILD
+		pacman_queuing; eval $INENGLISH PKGDEST=`pwd` nice -n 15 makepkg $confirmation --syncdeps --force -p ./PKGBUILD
 	else
-		$INENGLISH PKGDEST=`pwd` nice -n 15 makepkg $confirmation --force -p ./PKGBUILD
+		eval $INENGLISH PKGDEST=`pwd` nice -n 15 makepkg $confirmation --force -p ./PKGBUILD
 	fi
 fi
 
@@ -419,7 +419,7 @@ for package in $@; do
 	for file in ${files[@]}; do
 		echo -e "   ${COL_BLUE}-> ${NO_COLOR}${COL_BOLD}Downloading ${file%\?*} in build dir${NO_COLOR}"
 		filename=`echo ${file%*\?*} | sed "s/^.*\///"`
-		$INENGLISH wget --tries=3 --waitretry=3 --no-check-certificate "${url%\?*}$file" -O $filename
+		eval $INENGLISH wget --tries=3 --waitretry=3 --no-check-certificate "${url%\?*}$file" -O $filename
 	done
 
 	[ "$MAJOR" = "getpkgbuild" ] && return 0
@@ -1631,7 +1631,7 @@ case $MAJOR in
 		PKG=${args[0]}
 		#msg "Get PKGBUILD for $PKG"
 		if `is_unsupported $PKG`; then
-			$INENGLISH wget "http://aur.archlinux.org/packages/$PKG/$PKG.tar.gz" || { error "$PKG not found in AUR."; die 1; }
+			eval $INENGLISH wget "http://aur.archlinux.org/packages/$PKG/$PKG.tar.gz" || { error "$PKG not found in AUR."; die 1; }
 			tar xzf $PKG.tar.gz --transform="s,$PKG,," 2>/dev/null
 			rm $PKG.tar.gz
 		else
